version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: app
        container_name: user_service
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        ports:
            - 8080:8080
        depends_on:
            - redis

    redis:
        image: redis:7.2.3
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
        volumes:
            - cache:/data/cache

volumes:
    postgres-data:
    cache:
        driver: local
